<a href="https://colab.research.google.com/github/davidofitaly/notes_03_python_in_data_analysis/blob/main/01_the_basis_of_the_numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1.1 NumPy – Multidimensional Array

### Creating ndarray arrays

#####An `ndarray` (N-dimensional array) is the core data structure in NumPy. It is a fixed-size, homogeneous array that allows for efficient numerical operations. It is created using the `array` function.


####Examples 1.1

In [ ]:
data_1 = [10, 2.5, 0, 9, 5] # Define a Python list with numeric values
array_1 = np.array(data_1)  # Convert the list into a NumPy ndarray

array_1 # Display the NumPy array

array([10. ,  2.5,  0. ,  9. ,  5. ])

In [ ]:
data_2 = [[4,3,2,1], [9, 8, 7, 6]] # Define a Python list with numeric values
array_2 = np.array(data_2)  # Convert the list into a NumPy ndarray

array_2

array([[4, 3, 2, 1],
       [9, 8, 7, 6]])

### `ndim` and `shape` in NumPy

#####In NumPy, `ndim` and `shape` are attributes of an `ndarray` that describe its structure.

- **`ndim`**: Returns the number of dimensions (axes) of the array.
- **`shape`**: Returns a tuple representing the size of the array along each dimension.

####Examples 1.2

In [ ]:
array_1.ndim # Returns the number of dimensions of array_1

1

In [ ]:
array_2.shape # Returns the shape (size along each axis) of array_2

(2, 4)

### `dtype` in NumPy


- `dtype` stands for "data type" and is an attribute in NumPy that specifies the type of elements in an `ndarray`.
- It defines the type of data that the array holds, such as integers, floats, or strings.
- The `dtype` helps in determining the memory consumption and performance of operations.

####Examples 1.3

In [ ]:
array_1.dtype # array_1.dtype will display the data type of the elements in array_1

dtype('float64')

In [ ]:
array_2.dtype # array_2.dtype will show the data type of the elements in array_2

dtype('int64')

### Numpy Array Creation Functions



| Function      | Description                                                             | Example                                                                 |
|---------------|-------------------------------------------------------------------------|-------------------------------------------------------------------------|
| `array`       | Creates an array from a Python list or tuple.                           | `np.array([1, 2, 3])`                                                   |
| `asarray`     | Converts input to an ndarray, but does not copy if input is already ndarray. | `np.asarray([1, 2, 3])`                                                 |
| `arange`      | Returns an array with evenly spaced values within a specified range.     | `np.arange(0, 10, 2)`                                                  |
| `ones`        | Creates an array of ones with a specified shape and data type.          | `np.ones((2, 3))`                                                      |
| `ones_like`   | Returns an array of ones with the same shape and type as a given array. | `np.ones_like(array_1)`                                                |
| `zeros`       | Creates an array of zeros with a specified shape and data type.         | `np.zeros((2, 3))`                                                     |
| `zeros_like`  | Returns an array of zeros with the same shape and type as a given array. | `np.zeros_like(array_1)`                                               |
| `empty`       | Creates an uninitialized array with a specified shape.                  | `np.empty((2, 3))`                                                     |
| `empty_like`  | Returns an uninitialized array with the same shape and type as a given array. | `np.empty_like(array_1)`                                               |
| `full`        | Creates an array filled with a specified value.                          | `np.full((2, 3), 7)`                                                   |
| `full_like`   | Returns an array filled with a specified value, matching the shape and type of a given array. | `np.full_like(array_1, 7)`                                             |
| `eye`         | Creates a 2-D identity matrix with ones on the diagonal.                | `np.eye(3)`                                                            |
| `identity`    | Alias for `eye`. Creates a 2-D identity matrix.                         | `np.identity(3)`                                                       |


####Examples 1.4

In [ ]:
data_3 = [1,2,3,4,5]  # Define a Python list with numeric values
array_3 = np.array(data_3) # Convert the list into a NumPy ndarray

array_3 # Display the NumPy array

array([1, 2, 3, 4, 5])

In [ ]:
asaaray_1 = np.asarray(array_3) # If the input is already a NumPy array, it will return the same object without making a copy.

asaaray_1 # Display the resulting NumPy array

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(7) # It starts from 0 by default and increments by 1.

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
ones_array = np.ones((4,5))  # Creates a 4x5 array filled with ones.

ones_array # Displays the array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones_like = np.ones_like(ones_array) # Creates an array with the same shape and type as ones_1, filled with ones.

ones_like # Displays the new array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
zeros_array = np.zeros((2 ,3, 4)) # Creates a 3D array with shape (2, 3, 4), filled with zeros.

zeros_array # Displays the created array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
zeors_like_array = np.zeros_like(zeros_array) # Creates an array with the same shape and type as zeros_array, filled with zeros.

zeors_like_array # Displays the created array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
empty_array = np.empty((2, 3, 2)) # Creates an uninitialized array with the specified shape.

empty_array # Displays the created array

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
full_array = np.full((3, 4), 5) # Creates a 3x4 array filled with the value 5.

full_array # Displays the created array


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
full_like_array = np.full_like(full_array, 7) # Creates an array with the same shape and type as full_array, filled with the value 7.

full_like_array # Displays the created array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
eye_array = np.eye(5) # Creates a 5x5 identity matrix (ones on the diagonal, zeros elsewhere)

eye_array # Displays the created identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
identity_array = np.identity(5) # Creates a 5x5 identity matrix using the np.identity() function

identity_array # Displays the created identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `astype` in NumPy

- `astype()` is a method in NumPy that is used to **cast** or **convert** the data type of an existing array to a specified type.
- It creates a **new array** with the desired data type, leaving the original


In [ ]:
float_array = np.array([1.5, 2.3, 3.7, 4.9]) # Creating a NumPy array of floats

int_array = float_array.astype(int)  # Converts the float array to integers by truncating the decimal part

int_array # Displays the resulting integer array


array([1, 2, 3, 4])

In [ ]:
convert_to_string_array = np.array([1, 2, 3, 4], dtype=str) # Creates a NumPy array with integer elements and converts them to strings

convert_to_string_array # Displays the resulting array with string elements


array(['1', '2', '3', '4'], dtype='<U1')

In [ ]:
convert_to_float_array = np.array([1, 2, 3, 4], dtype=float) # Creates a NumPy array with integer elements and converts them to floats

convert_to_float_array # Displays the resulting array with float elements

array([1., 2., 3., 4.])

### Arithmetic Operations with NumPy Arrays

#####NumPy provides efficient and vectorized arithmetic operations on arrays, allowing you to perform element-wise operations directly on arrays without the need for explicit loops. These operations are typically faster and more efficient compared to traditional Python loops.

##### Basic Arithmetic Operations:
1. **Addition (`+`)**: Adds corresponding elements of two arrays.
2. **Subtraction (`-`)**: Subtracts corresponding elements of one array from another.
3. **Multiplication (`*`)**: Multiplies corresponding elements of two arrays.
4. **Division (`/`)**: Divides corresponding elements of one array by another.
5. **Exponentiation (`^`)**: Raises each element of the array to the power of the corresponding element in another array.
6. **Modulo (`%`)**: Computes the remainder of the division of corresponding elements.

####Examples 1.5

In [ ]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
# Addition
add_result = a + b
print("Addition:", add_result)

Addition: [5 7 9]


In [ ]:
# Subtraction
sub_result = a - b
print("Subtraction:", sub_result)

Subtraction: [-3 -3 -3]


In [ ]:
# Multiplication
mul_result = a * b
print("Multiplication:", mul_result)

Multiplication: [ 4 10 18]


In [ ]:
# Division
div_result = a / b
print("Division:", div_result)

Division: [0.25 0.4  0.5 ]


In [ ]:
# Exponentiation
exp_result = a ** b
print("Exponentiation:", exp_result)

Exponentiation: [  1  32 729]


In [ ]:
# Modulo
mod_result = a % b
print("Modulo:", mod_result)

Modulo: [1 2 3]


### Indexing in NumPy Arrays


#####Indexing in NumPy allows you to access and modify elements in an array using their positions. You can access elements using a single index, multiple indices, or slices. NumPy also supports advanced indexing techniques, including boolean indexing and fancy indexing.


####Examples 1.6



*   Basics of indexing





In [ ]:
array3d = np.array([[[8, 7, 1], [4, 7, 6]], [[7, 5, 9], [2, 11, 0]]])
array3d

array([[[ 8,  7,  1],
        [ 4,  7,  6]],

       [[ 7,  5,  9],
        [ 2, 11,  0]]])

In [ ]:
array3d[0] # Accessing the first 2D slice (row) of the 3D array 'array3d'.

array([[8, 7, 1],
       [4, 7, 6]])

In [ ]:
array3d[1] # Accessing the second 2D slice (row) of the 3D array 'array3d'.

array([[ 7,  5,  9],
       [ 2, 11,  0]])



*   Indexing by means of clippings



In [ ]:
array2d = np.array([[1,2,3], [5,9,1], [2,7,0]])
array2d

array([[1, 2, 3],
       [5, 9, 1],
       [2, 7, 0]])

In [ ]:
array2d[:2, 1:]

array([[2, 3],
       [9, 1]])

In [ ]:
array2d[2, :]

array([2, 7, 0])

In [ ]:
array2d[:, :2]

array([[1, 2],
       [5, 9],
       [2, 7]])

In [ ]:
array2d[2, 2]

0

In [ ]:
array2d[1, :2]

array([5, 9])



*   Indexing and logical values


In [ ]:
names_array = np.array(["John", "Alice", "Bob", "Emma", "James", "Sophia", "John"])
data_array = np.array([[4,7], [8,2], [0,5], [4,8], [2,3], [9,6], [1, 6]])

print(names_array)
print(data_array)

['John' 'Alice' 'Bob' 'Emma' 'James' 'Sophia' 'John']
[[4 7]
 [8 2]
 [0 5]
 [4 8]
 [2 3]
 [9 6]
 [1 6]]


In [ ]:
names_array == "John"

array([ True, False, False, False, False, False,  True])

In [ ]:
data_array[names_array =="Emma"]

array([[4, 8]])

In [ ]:
data_array[names_array == "John"]

array([[4, 7],
       [1, 6]])

In [ ]:
names_array != "Sophia"

array([ True,  True,  True,  True,  True, False,  True])

In [ ]:
data_array[~(names_array == "James")]

array([[4, 7],
       [8, 2],
       [0, 5],
       [4, 8],
       [9, 6],
       [1, 6]])

In [ ]:
mask = (names_array == "Alice") | (names_array == "Bob")
data_array[mask]

array([[8, 2],
       [0, 5]])

In [ ]:
data_array[data_array < 5] = 0
data_array

array([[0, 7],
       [8, 0],
       [0, 5],
       [0, 8],
       [0, 0],
       [9, 6],
       [0, 6]])

In [ ]:
data_array[names_array !="Emma"] = 9
data_array

array([[9, 9],
       [9, 9],
       [9, 9],
       [0, 8],
       [9, 9],
       [9, 9],
       [9, 9]])



*   Fancy indexing



In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]]) # Creating a 2D NumPy array with shape (3, 2)

fancy_arr = arr[[1, 0], [0, 1]] # Fancy indexing: Selecting elements at positions (1, 0) and (0, 1)
fancy_arr  # Displays the resulting

array([3, 2])

In [ ]:
arr = np.array([[1, 2, 3], [3, 4, 9], [5, 6, 0]]) # Creating a 2D NumPy array with shape (3, 3)

fancy_arr = arr[[2, 1 ], [0, 2]] # Fancy indexing: Selecting elements at positions (1, 0) and (0, 1)
fancy_arr  # Displays the resulting

array([5, 9])

### Transposing Arrays in NumPy


- **Transpose**: Transposing an array means flipping it over its diagonal, converting rows to columns and vice versa.
- **Function**: You can transpose a NumPy array using `.T` or `np.transpose()`.

In [ ]:
arr = np.array([[1, 2], [3, 4]]) # Creating a 2D array

transposed_arr = np.transpose(arr) # Transposing the array

transposed_arr # Printing the transposed array

array([[1, 3],
       [2, 4]])

In [ ]:
arr = np.arange(15).reshape(3,5) # Create an array of integers from 0 to 14, and reshape it to a 3x5 matrix

arr.T # Transpose the array, swapping its rows and columns

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 1.2 Generation of pseudo-random numbers

### Generating Pseudorandom Numbers in NumPy

- **Pseudorandom numbers** are numbers generated by an algorithm that mimics randomness. While the numbers appear random, they are actually deterministic, based on a starting value called the **seed**.
  
- **NumPy's `random` module** provides a wide range of functions to generate pseudorandom numbers, such as:
  
  - `np.random.rand()`: Generates numbers from a uniform distribution between 0 and 1.
  - `np.random.randint()`: Generates random integers within a specified range.
  - `np.random.randn()`: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
  - `np.random.choice()`: Randomly selects elements from an array.

- **Setting the seed**:
  - The `np.random.seed()` function is used to set the seed, allowing you to generate the same sequence of random numbers every time the code is run (useful for reproducibility).

In [9]:
np.random.seed(42) # Set the seed for reproducibility, so the random numbers will be the same each time

random_float = np.random.rand(15).reshape(3,5) # Generate 15 random numbers from a uniform distribution between 0 and 1

print(random_float) # Print the resulting 3x5 matrix of random numbers


[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]]


In [11]:
random_int = np.random.randint(5, size=(1, 11)) # Generate 11 random integers between 0 and 4 (inclusive) and reshape them into a 1x11 array

print(random_int) # Print the resulting array of random integers

[[0 3 1 4 3 0 0 2 2 1 3]]


In [14]:
random_rand = np.random.rand(10) # Generate an array of 10 random float numbers between 0 and 1 using a uniform distribution

print(random_rand) # Print the resulting array of random floats

[0.17336465 0.39106061 0.18223609 0.75536141 0.42515587 0.20794166
 0.56770033 0.03131329 0.84228477 0.44975413]
